version: '3.8'

services:
  bot:
    build: .
    container_name: wa_tg_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./sessions:/app/sessions
      - ./logs:/app/logs
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge

