services:
    directus:
        image: directus/directus:11.5.1
        ports:
            - 8055:8055
        volumes:
            - ./database:/directus/database
            - ./uploads:/directus/uploads
            - ./extensions:/directus/extensions
        environment:
            SECRET: "replace-with-secure-random-value-for-production"
            ADMIN_EMAIL: "seocos@gmail.com"
            ADMIN_PASSWORD: "directus2024!"
            DB_CLIENT: "sqlite3"
            DB_FILENAME: "/directus/database/data.db"
            WEBSOCKETS_ENABLED: "true"
            PUBLIC_URL: "http://localhost:8055"
        restart: unless-stopped
